%============================================================
% clarion_llvm.pl - LLVM IR Code Generator for Clarion
%
% Generates LLVM IR text (.ll files) from Clarion AST.
% Uses direct text emission - no LLVM library dependencies.
%
% Usage:
%   ?- compile_to_llvm('program.clw', 'program.ll').
%   ?- compile_ast_to_llvm(AST, IRText).
%============================================================

:- module(clarion_llvm, [
    compile_to_llvm/2,          % compile_to_llvm(+ClarionFile, +OutputFile)
    compile_ast_to_llvm/2,      % compile_ast_to_llvm(+AST, -IRText)
    compile_ast_to_llvm/3       % compile_ast_to_llvm(+AST, +Options, -IRText)
]).

:- use_module(parser).
:- use_module(library(lists)).
:- use_module(library(apply)).

%============================================================
% Compilation State
%
% Tracks: temp counter, label counter, string literals,
% current function, variable -> register mapping
%============================================================

empty_codegen_state(state{
    temp_counter: 0,
    label_counter: 0,
    strings: [],
    current_func: none,
    vars: [],           % [(Name, LLVMReg), ...]
    globals: [],        % [(Name, Type), ...]
    procedures: []      % [procedure(...), ...]
}).

%------------------------------------------------------------
% State Accessors
%------------------------------------------------------------

next_temp(StateIn, Temp, StateOut) :-
    N = StateIn.temp_counter,
    format(atom(Temp), '%~d', [N]),
    N1 is N + 1,
    StateOut = StateIn.put(temp_counter, N1).

next_label(StateIn, Label, StateOut) :-
    N = StateIn.label_counter,
    format(atom(Label), 'L~d', [N]),
    N1 is N + 1,
    StateOut = StateIn.put(label_counter, N1).

add_string_literal(String, StateIn, Index, StateOut) :-
    Strings = StateIn.strings,
    length(Strings, Index),
    StateOut = StateIn.put(strings, [String|Strings]).

get_var_reg(Name, State, Reg) :-
    member((Name, Reg), State.vars), !.
get_var_reg(Name, _State, Reg) :-
    % Global variable reference
    format(atom(Reg), '@~w', [Name]).

set_var_reg(Name, Reg, StateIn, StateOut) :-
    Vars = StateIn.vars,
    ( select((Name, _), Vars, RestVars)
    -> NewVars = [(Name, Reg)|RestVars]
    ;  NewVars = [(Name, Reg)|Vars]
    ),
    StateOut = StateIn.put(vars, NewVars).

%============================================================
% Main Entry Points
%============================================================

%% compile_to_llvm(+ClarionFile, +OutputFile) is det.
%
% Parse a Clarion file and compile to LLVM IR.

compile_to_llvm(ClarionFile, OutputFile) :-
    parser:parse_file(ClarionFile, AST),
    compile_ast_to_llvm(AST, IRText),
    open(OutputFile, write, Stream),
    write(Stream, IRText),
    close(Stream),
    format("Compiled ~w -> ~w~n", [ClarionFile, OutputFile]).

%% compile_ast_to_llvm(+AST, -IRText) is det.
%
% Compile Clarion AST to LLVM IR text.

compile_ast_to_llvm(AST, IRText) :-
    compile_ast_to_llvm(AST, _{}, IRText).

compile_ast_to_llvm(AST, _Options, IRText) :-
    empty_codegen_state(InitState),
    codegen_program(AST, InitState, FinalState, ProgramIR),
    generate_preamble(Preamble),
    generate_string_constants(FinalState.strings, StringDefs),
    generate_runtime_decls(RuntimeDecls),
    atomics_to_string([Preamble, StringDefs, RuntimeDecls, ProgramIR], IRText).

%============================================================
% LLVM IR Preamble
%============================================================

generate_preamble(Preamble) :-
    Preamble = "; Generated by Clarion LLVM Codegen\n\
target triple = \"x86_64-pc-linux-gnu\"\n\n\
; Clarion string type (length-prefixed)\n\
%String = type { i32, [256 x i8] }\n\n".

generate_runtime_decls(Decls) :-
    Decls = "; Runtime function declarations\n\
declare i32 @printf(i8*, ...)\n\
declare i32 @puts(i8*)\n\
declare i8* @malloc(i64)\n\
declare void @free(i8*)\n\
declare i64 @strlen(i8*)\n\
declare i8* @strcpy(i8*, i8*)\n\
declare i8* @strcat(i8*, i8*)\n\
declare i32 @strcmp(i8*, i8*)\n\n".

%============================================================
% String Constants
%============================================================

generate_string_constants(Strings, Defs) :-
    reverse(Strings, OrderedStrings),
    generate_string_constants_(OrderedStrings, 0, Defs).

generate_string_constants_([], _, "").
generate_string_constants_([Str|Rest], Idx, Defs) :-
    atom_length(Str, Len),
    Len1 is Len + 1,
    format(atom(Def), '@.str.~d = private constant [~d x i8] c"~w\\00"\n',
           [Idx, Len1, Str]),
    Idx1 is Idx + 1,
    generate_string_constants_(Rest, Idx1, RestDefs),
    atom_concat(Def, RestDefs, Defs).

%============================================================
% Program Structure Codegen
%============================================================

codegen_program(program(_, GlobalDecls, code(MainStmts), Procedures),
                StateIn, StateOut, IR) :-
    % Register all procedures first
    register_procedures(Procedures, StateIn, State1),
    % Generate global variables
    codegen_globals(GlobalDecls, State1, State2, GlobalsIR),
    % Generate procedure definitions
    codegen_procedures(Procedures, State2, State3, ProcsIR),
    % Generate main function
    codegen_main(MainStmts, State3, StateOut, MainIR),
    atomics_to_string([GlobalsIR, ProcsIR, MainIR], IR).

register_procedures([], State, State).
register_procedures([Proc|Procs], StateIn, StateOut) :-
    ( Proc = procedure(Name, _, _, _)
    ; Proc = routine(Name, _)
    ),
    !,
    ExistingProcs = StateIn.procedures,
    State1 = StateIn.put(procedures, [Proc|ExistingProcs]),
    register_procedures(Procs, State1, StateOut).
register_procedures([_|Procs], StateIn, StateOut) :-
    register_procedures(Procs, StateIn, StateOut).

%============================================================
% Global Variables
%============================================================

codegen_globals([], State, State, "").
codegen_globals([Decl|Decls], StateIn, StateOut, IR) :-
    codegen_global(Decl, StateIn, State1, DeclIR),
    codegen_globals(Decls, State1, StateOut, RestIR),
    atom_concat(DeclIR, RestIR, IR).

codegen_global(var(Name, Type, SizeSpec), StateIn, StateOut, IR) :-
    clarion_to_llvm_type(Type, SizeSpec, LLVMType),
    default_llvm_value(LLVMType, DefaultVal),
    format(atom(IR), '@~w = global ~w ~w\n', [Name, LLVMType, DefaultVal]),
    Globals = StateIn.globals,
    StateOut = StateIn.put(globals, [(Name, LLVMType)|Globals]).

% Skip non-variable declarations for now
codegen_global(_, State, State, "").

%============================================================
% Type Mapping
%============================================================

clarion_to_llvm_type('LONG', _, 'i64').
clarion_to_llvm_type('SHORT', _, 'i32').
clarion_to_llvm_type('BYTE', _, 'i8').
clarion_to_llvm_type('REAL', _, 'double').
clarion_to_llvm_type('SREAL', _, 'float').
clarion_to_llvm_type('DATE', _, 'i32').
clarion_to_llvm_type('TIME', _, 'i32').
clarion_to_llvm_type('DECIMAL', size(P, _), Type) :-
    ( P =< 9 -> Type = 'i32' ; Type = 'i64' ).
clarion_to_llvm_type('DECIMAL', _, 'i64').
clarion_to_llvm_type('STRING', size(N), Type) :-
    format(atom(Type), '[~d x i8]', [N]).
clarion_to_llvm_type('STRING', _, '[256 x i8]').
clarion_to_llvm_type('CSTRING', size(N), Type) :-
    format(atom(Type), '[~d x i8]', [N]).
clarion_to_llvm_type('CSTRING', _, 'i8*').
clarion_to_llvm_type('PSTRING', _, 'i8*').
clarion_to_llvm_type(custom(_), _, 'i8*').  % Object pointer
clarion_to_llvm_type(_, _, 'i64').  % Default to i64

default_llvm_value('i64', '0').
default_llvm_value('i32', '0').
default_llvm_value('i16', '0').
default_llvm_value('i8', '0').
default_llvm_value('double', '0.0').
default_llvm_value('float', '0.0').
default_llvm_value('i8*', 'null').
default_llvm_value(Type, Val) :-
    atom_string(Type, TypeStr),
    ( sub_string(TypeStr, 0, _, _, "[")
    -> Val = 'zeroinitializer'
    ;  Val = '0'
    ).

%============================================================
% Procedure Codegen
%============================================================

codegen_procedures([], State, State, "").
codegen_procedures([Proc|Procs], StateIn, StateOut, IR) :-
    codegen_procedure(Proc, StateIn, State1, ProcIR),
    codegen_procedures(Procs, State1, StateOut, RestIR),
    atom_concat(ProcIR, RestIR, IR).

codegen_procedure(procedure(Name, Params, LocalVars, code(Body)),
                  StateIn, StateOut, IR) :-
    % Reset temp/label counters for new function
    State1 = StateIn.put(temp_counter, 0).put(label_counter, 0).put(vars, []),
    % Generate parameter list
    codegen_params(Params, ParamList, ParamTypes),
    % Determine return type (default to i64)
    ReturnType = 'i64',
    % Generate function header
    format(atom(Header), '\ndefine ~w @~w(~w) {\n', [ReturnType, Name, ParamList]),
    format(atom(Entry), 'entry:\n', []),
    % Allocate parameters on stack
    codegen_param_allocs(Params, ParamTypes, State1, State2, ParamAllocIR),
    % Allocate local variables
    codegen_local_allocs(LocalVars, State2, State3, LocalAllocIR),
    % Generate body
    codegen_statements(Body, State3, State4, BodyIR),
    % Ensure function ends with ret
    format(atom(DefaultRet), '  ret i64 0\n', []),
    format(atom(Footer), '}\n', []),
    atomics_to_string([Header, Entry, ParamAllocIR, LocalAllocIR, BodyIR,
                       DefaultRet, Footer], IR),
    StateOut = State4.

codegen_procedure(routine(Name, Body), StateIn, StateOut, IR) :-
    % Routines become void functions
    State1 = StateIn.put(temp_counter, 0).put(label_counter, 0).put(vars, []),
    format(atom(Header), '\ndefine void @routine_~w() {\n', [Name]),
    format(atom(Entry), 'entry:\n', []),
    codegen_statements(Body, State1, State2, BodyIR),
    format(atom(Footer), '  ret void\n}\n', []),
    atomics_to_string([Header, Entry, BodyIR, Footer], IR),
    StateOut = State2.

% Skip method implementations for now
codegen_procedure(method_impl(_, _, _, _, _), State, State, "").

%------------------------------------------------------------
% Parameters
%------------------------------------------------------------

codegen_params([], "", []).
codegen_params([Param|Params], ParamList, [Type|Types]) :-
    codegen_param(Param, ParamStr, Type),
    codegen_params(Params, RestParams, Types),
    ( RestParams = ""
    -> ParamList = ParamStr
    ;  format(atom(ParamList), '~w, ~w', [ParamStr, RestParams])
    ).

codegen_param(param(Type, Name), ParamStr, LLVMType) :-
    clarion_to_llvm_type(Type, none, LLVMType),
    format(atom(ParamStr), '~w %param_~w', [LLVMType, Name]).
codegen_param(param(Type, Name, optional, _), ParamStr, LLVMType) :-
    clarion_to_llvm_type(Type, none, LLVMType),
    format(atom(ParamStr), '~w %param_~w', [LLVMType, Name]).

codegen_param_allocs([], [], State, State, "").
codegen_param_allocs([Param|Params], [Type|Types], StateIn, StateOut, IR) :-
    ( Param = param(_, Name) ; Param = param(_, Name, _, _) ),
    format(atom(AllocIR), '  %~w = alloca ~w\n  store ~w %param_~w, ~w* %~w\n',
           [Name, Type, Type, Name, Type, Name]),
    set_var_reg(Name, Name, StateIn, State1),
    codegen_param_allocs(Params, Types, State1, StateOut, RestIR),
    atom_concat(AllocIR, RestIR, IR).

%------------------------------------------------------------
% Local Variables
%------------------------------------------------------------

codegen_local_allocs([], State, State, "").
codegen_local_allocs([LocalVar|Rest], StateIn, StateOut, IR) :-
    ( LocalVar = local_var(Name, Type, SizeSpec)
    ; LocalVar = var(Name, Type, SizeSpec)
    ),
    !,
    clarion_to_llvm_type(Type, SizeSpec, LLVMType),
    default_llvm_value(LLVMType, DefaultVal),
    format(atom(AllocIR), '  %~w = alloca ~w\n  store ~w ~w, ~w* %~w\n',
           [Name, LLVMType, LLVMType, DefaultVal, LLVMType, Name]),
    set_var_reg(Name, Name, StateIn, State1),
    codegen_local_allocs(Rest, State1, StateOut, RestIR),
    atom_concat(AllocIR, RestIR, IR).
codegen_local_allocs([_|Rest], StateIn, StateOut, IR) :-
    codegen_local_allocs(Rest, StateIn, StateOut, IR).

%============================================================
% Main Function
%============================================================

codegen_main(Statements, StateIn, StateOut, IR) :-
    State1 = StateIn.put(temp_counter, 0).put(label_counter, 0),
    format(atom(Header), '\ndefine i32 @main() {\n', []),
    format(atom(Entry), 'entry:\n', []),
    codegen_statements(Statements, State1, StateOut, BodyIR),
    format(atom(Footer), '  ret i32 0\n}\n', []),
    atomics_to_string([Header, Entry, BodyIR, Footer], IR).

%============================================================
% Statement Codegen
%============================================================

codegen_statements([], State, State, "").
codegen_statements([Stmt|Stmts], StateIn, StateOut, IR) :-
    codegen_statement(Stmt, StateIn, State1, StmtIR),
    codegen_statements(Stmts, State1, StateOut, RestIR),
    atom_concat(StmtIR, RestIR, IR).

%------------------------------------------------------------
% Assignment: Var = Expr
%------------------------------------------------------------

codegen_statement(assign(VarName, Expr), StateIn, StateOut, IR) :-
    codegen_expr(Expr, StateIn, State1, ExprResult, ExprIR),
    ( member((VarName, _), State1.vars)
    -> % Local variable
       format(atom(StoreIR), '  store i64 ~w, i64* %~w\n', [ExprResult, VarName]),
       StateOut = State1
    ;  % Global variable
       format(atom(StoreIR), '  store i64 ~w, i64* @~w\n', [ExprResult, VarName]),
       StateOut = State1
    ),
    atom_concat(ExprIR, StoreIR, IR).

%------------------------------------------------------------
% Procedure Call
%------------------------------------------------------------

codegen_statement(call(Name, Args), StateIn, StateOut, IR) :-
    codegen_call(Name, Args, StateIn, StateOut, _, IR).

%------------------------------------------------------------
% IF Statement
%------------------------------------------------------------

codegen_statement(if(Cond, ThenStmts, ElsifClauses, ElseStmts),
                  StateIn, StateOut, IR) :-
    % Generate labels
    next_label(StateIn, ThenLabel, State1),
    next_label(State1, ElseLabel, State2),
    next_label(State2, EndLabel, State3),
    % Generate condition
    codegen_expr(Cond, State3, State4, CondResult, CondIR),
    % Compare to zero (truthy test)
    next_temp(State4, CmpResult, State5),
    format(atom(CmpIR), '  ~w = icmp ne i64 ~w, 0\n', [CmpResult, CondResult]),
    format(atom(BrIR), '  br i1 ~w, label %~w, label %~w\n',
           [CmpResult, ThenLabel, ElseLabel]),
    % Then block
    format(atom(ThenLabelIR), '~w:\n', [ThenLabel]),
    codegen_statements(ThenStmts, State5, State6, ThenBodyIR),
    format(atom(ThenBrIR), '  br label %~w\n', [EndLabel]),
    % Else block (including elsif handling)
    format(atom(ElseLabelIR), '~w:\n', [ElseLabel]),
    ( ElsifClauses = []
    -> codegen_statements(ElseStmts, State6, State7, ElseBodyIR)
    ;  codegen_elsifs(ElsifClauses, ElseStmts, EndLabel, State6, State7, ElseBodyIR)
    ),
    format(atom(ElseBrIR), '  br label %~w\n', [EndLabel]),
    % End label
    format(atom(EndLabelIR), '~w:\n', [EndLabel]),
    atomics_to_string([CondIR, CmpIR, BrIR, ThenLabelIR, ThenBodyIR, ThenBrIR,
                       ElseLabelIR, ElseBodyIR, ElseBrIR, EndLabelIR], IR),
    StateOut = State7.

% 3-arg IF form (no elsif)
codegen_statement(if(Cond, ThenStmts, ElseStmts), StateIn, StateOut, IR) :-
    \+ ElseStmts = [elsif(_, _)|_],
    codegen_statement(if(Cond, ThenStmts, [], ElseStmts), StateIn, StateOut, IR).

codegen_elsifs([], ElseStmts, _, StateIn, StateOut, IR) :-
    codegen_statements(ElseStmts, StateIn, StateOut, IR).
codegen_elsifs([elsif(Cond, Stmts)|Rest], ElseStmts, EndLabel,
               StateIn, StateOut, IR) :-
    next_label(StateIn, ThenLabel, State1),
    next_label(State1, NextLabel, State2),
    codegen_expr(Cond, State2, State3, CondResult, CondIR),
    next_temp(State3, CmpResult, State4),
    format(atom(CmpIR), '  ~w = icmp ne i64 ~w, 0\n', [CmpResult, CondResult]),
    format(atom(BrIR), '  br i1 ~w, label %~w, label %~w\n',
           [CmpResult, ThenLabel, NextLabel]),
    format(atom(ThenLabelIR), '~w:\n', [ThenLabel]),
    codegen_statements(Stmts, State4, State5, ThenBodyIR),
    format(atom(ThenBrIR), '  br label %~w\n', [EndLabel]),
    format(atom(NextLabelIR), '~w:\n', [NextLabel]),
    codegen_elsifs(Rest, ElseStmts, EndLabel, State5, StateOut, RestIR),
    atomics_to_string([CondIR, CmpIR, BrIR, ThenLabelIR, ThenBodyIR,
                       ThenBrIR, NextLabelIR, RestIR], IR).

%------------------------------------------------------------
% LOOP TO (for loop)
%------------------------------------------------------------

codegen_statement(loop_to(Var, FromExpr, ToExpr, Body), StateIn, StateOut, IR) :-
    % Allocate loop variable if not exists
    ( member((Var, _), StateIn.vars)
    -> AllocIR = "", State1 = StateIn
    ;  format(atom(AllocIR), '  %~w = alloca i64\n', [Var]),
       set_var_reg(Var, Var, StateIn, State1)
    ),
    % Generate from/to values
    codegen_expr(FromExpr, State1, State2, FromResult, FromIR),
    codegen_expr(ToExpr, State2, State3, ToResult, ToIR),
    % Store initial value
    format(atom(InitIR), '  store i64 ~w, i64* %~w\n', [FromResult, Var]),
    % Generate labels
    next_label(State3, CondLabel, State4),
    next_label(State4, BodyLabel, State5),
    next_label(State5, IncrLabel, State6),
    next_label(State6, EndLabel, State7),
    % Branch to condition check
    format(atom(InitBrIR), '  br label %~w\n', [CondLabel]),
    % Condition block
    format(atom(CondLabelIR), '~w:\n', [CondLabel]),
    next_temp(State7, LoadResult, State8),
    format(atom(LoadIR), '  ~w = load i64, i64* %~w\n', [LoadResult, Var]),
    next_temp(State8, CmpResult, State9),
    format(atom(CmpIR), '  ~w = icmp sle i64 ~w, ~w\n',
           [CmpResult, LoadResult, ToResult]),
    format(atom(CondBrIR), '  br i1 ~w, label %~w, label %~w\n',
           [CmpResult, BodyLabel, EndLabel]),
    % Body block
    format(atom(BodyLabelIR), '~w:\n', [BodyLabel]),
    % Save loop context for break/cycle
    State10 = State9.put(loop_end, EndLabel).put(loop_incr, IncrLabel),
    codegen_statements(Body, State10, State11, BodyIR),
    format(atom(BodyBrIR), '  br label %~w\n', [IncrLabel]),
    % Increment block
    format(atom(IncrLabelIR), '~w:\n', [IncrLabel]),
    next_temp(State11, CurrVal, State12),
    format(atom(LoadCurrIR), '  ~w = load i64, i64* %~w\n', [CurrVal, Var]),
    next_temp(State12, NextVal, State13),
    format(atom(IncrIR), '  ~w = add i64 ~w, 1\n', [NextVal, CurrVal]),
    format(atom(StoreIncrIR), '  store i64 ~w, i64* %~w\n', [NextVal, Var]),
    format(atom(IncrBrIR), '  br label %~w\n', [CondLabel]),
    % End block
    format(atom(EndLabelIR), '~w:\n', [EndLabel]),
    atomics_to_string([AllocIR, FromIR, ToIR, InitIR, InitBrIR,
                       CondLabelIR, LoadIR, CmpIR, CondBrIR,
                       BodyLabelIR, BodyIR, BodyBrIR,
                       IncrLabelIR, LoadCurrIR, IncrIR, StoreIncrIR, IncrBrIR,
                       EndLabelIR], IR),
    StateOut = State13.

%------------------------------------------------------------
% LOOP WHILE
%------------------------------------------------------------

codegen_statement(loop_while(Cond, Body), StateIn, StateOut, IR) :-
    next_label(StateIn, CondLabel, State1),
    next_label(State1, BodyLabel, State2),
    next_label(State2, EndLabel, State3),
    format(atom(InitBrIR), '  br label %~w\n', [CondLabel]),
    format(atom(CondLabelIR), '~w:\n', [CondLabel]),
    codegen_expr(Cond, State3, State4, CondResult, CondIR),
    next_temp(State4, CmpResult, State5),
    format(atom(CmpIR), '  ~w = icmp ne i64 ~w, 0\n', [CmpResult, CondResult]),
    format(atom(CondBrIR), '  br i1 ~w, label %~w, label %~w\n',
           [CmpResult, BodyLabel, EndLabel]),
    format(atom(BodyLabelIR), '~w:\n', [BodyLabel]),
    State6 = State5.put(loop_end, EndLabel).put(loop_cond, CondLabel),
    codegen_statements(Body, State6, State7, BodyIR),
    format(atom(BodyBrIR), '  br label %~w\n', [CondLabel]),
    format(atom(EndLabelIR), '~w:\n', [EndLabel]),
    atomics_to_string([InitBrIR, CondLabelIR, CondIR, CmpIR, CondBrIR,
                       BodyLabelIR, BodyIR, BodyBrIR, EndLabelIR], IR),
    StateOut = State7.

%------------------------------------------------------------
% LOOP (infinite)
%------------------------------------------------------------

codegen_statement(loop(Body), StateIn, StateOut, IR) :-
    next_label(StateIn, LoopLabel, State1),
    next_label(State1, EndLabel, State2),
    format(atom(InitBrIR), '  br label %~w\n', [LoopLabel]),
    format(atom(LoopLabelIR), '~w:\n', [LoopLabel]),
    State3 = State2.put(loop_end, EndLabel).put(loop_cond, LoopLabel),
    codegen_statements(Body, State3, State4, BodyIR),
    format(atom(BodyBrIR), '  br label %~w\n', [LoopLabel]),
    format(atom(EndLabelIR), '~w:\n', [EndLabel]),
    atomics_to_string([InitBrIR, LoopLabelIR, BodyIR, BodyBrIR, EndLabelIR], IR),
    StateOut = State4.

%------------------------------------------------------------
% BREAK / CYCLE
%------------------------------------------------------------

codegen_statement(break, StateIn, StateIn, IR) :-
    EndLabel = StateIn.loop_end,
    format(atom(IR), '  br label %~w\n', [EndLabel]).

codegen_statement(cycle, StateIn, StateIn, IR) :-
    ( get_dict(loop_incr, StateIn, IncrLabel)
    -> Label = IncrLabel  % LOOP TO uses increment label
    ;  Label = StateIn.loop_cond  % WHILE/infinite uses condition label
    ),
    format(atom(IR), '  br label %~w\n', [Label]).

%------------------------------------------------------------
% RETURN
%------------------------------------------------------------

codegen_statement(return, State, State, "  ret i64 0\n").

codegen_statement(return(Expr), StateIn, StateOut, IR) :-
    codegen_expr(Expr, StateIn, StateOut, Result, ExprIR),
    format(atom(RetIR), '  ret i64 ~w\n', [Result]),
    atom_concat(ExprIR, RetIR, IR).

%------------------------------------------------------------
% CASE Statement
%------------------------------------------------------------

codegen_statement(case(Expr, Cases, ElseStmts), StateIn, StateOut, IR) :-
    codegen_expr(Expr, StateIn, State1, ExprResult, ExprIR),
    next_label(State1, DefaultLabel, State2),
    next_label(State2, EndLabel, State3),
    % Generate switch cases
    generate_case_labels(Cases, State3, State4, CaseLabels),
    format_switch_cases(CaseLabels, ExprResult, SwitchCases),
    format(atom(SwitchIR), '  switch i64 ~w, label %~w [\n~w  ]\n',
           [ExprResult, DefaultLabel, SwitchCases]),
    % Generate case blocks
    codegen_case_blocks(Cases, CaseLabels, EndLabel, State4, State5, CaseBlocksIR),
    % Default block
    format(atom(DefaultLabelIR), '~w:\n', [DefaultLabel]),
    codegen_statements(ElseStmts, State5, State6, DefaultBodyIR),
    format(atom(DefaultBrIR), '  br label %~w\n', [EndLabel]),
    % End label
    format(atom(EndLabelIR), '~w:\n', [EndLabel]),
    atomics_to_string([ExprIR, SwitchIR, CaseBlocksIR, DefaultLabelIR,
                       DefaultBodyIR, DefaultBrIR, EndLabelIR], IR),
    StateOut = State6.

generate_case_labels([], State, State, []).
generate_case_labels([case_of(Val, _)|Rest], StateIn, StateOut, [(Val, Label)|Labels]) :-
    next_label(StateIn, Label, State1),
    generate_case_labels(Rest, State1, StateOut, Labels).

format_switch_cases([], _, "").
format_switch_cases([(Val, Label)|Rest], _, Cases) :-
    ( Val = number(N) -> Value = N ; Value = Val ),
    format(atom(Case), '    i64 ~w, label %~w\n', [Value, Label]),
    format_switch_cases(Rest, _, RestCases),
    atom_concat(Case, RestCases, Cases).

codegen_case_blocks([], [], _, State, State, "").
codegen_case_blocks([case_of(_, Stmts)|Cases], [(_, Label)|Labels], EndLabel,
                    StateIn, StateOut, IR) :-
    format(atom(LabelIR), '~w:\n', [Label]),
    codegen_statements(Stmts, StateIn, State1, BodyIR),
    format(atom(BrIR), '  br label %~w\n', [EndLabel]),
    codegen_case_blocks(Cases, Labels, EndLabel, State1, StateOut, RestIR),
    atomics_to_string([LabelIR, BodyIR, BrIR, RestIR], IR).

%------------------------------------------------------------
% DO (routine call)
%------------------------------------------------------------

codegen_statement(do(RoutineName), State, State, IR) :-
    format(atom(IR), '  call void @routine_~w()\n', [RoutineName]).

%------------------------------------------------------------
% Compound Assignment
%------------------------------------------------------------

codegen_statement(assign_add(VarName, Expr), StateIn, StateOut, IR) :-
    codegen_expr(Expr, StateIn, State1, ExprResult, ExprIR),
    next_temp(State1, LoadResult, State2),
    next_temp(State2, AddResult, State3),
    ( member((VarName, _), State3.vars)
    -> VarRef = VarName, Prefix = '%'
    ;  VarRef = VarName, Prefix = '@'
    ),
    format(atom(LoadIR), '  ~w = load i64, i64* ~w~w\n',
           [LoadResult, Prefix, VarRef]),
    format(atom(AddIR), '  ~w = add i64 ~w, ~w\n',
           [AddResult, LoadResult, ExprResult]),
    format(atom(StoreIR), '  store i64 ~w, i64* ~w~w\n',
           [AddResult, Prefix, VarRef]),
    atomics_to_string([ExprIR, LoadIR, AddIR, StoreIR], IR),
    StateOut = State3.

%------------------------------------------------------------
% No-op statements
%------------------------------------------------------------

codegen_statement(beep, State, State, "").
codegen_statement(display, State, State, "").
codegen_statement(exit, State, State, "  ret void\n").
codegen_statement(select(_), State, State, "").
codegen_statement(control_prop_assign(_, _, _), State, State, "").
codegen_statement(prop_assign(_, _, _), State, State, "").

%------------------------------------------------------------
% Member assignment (simplified)
%------------------------------------------------------------

codegen_statement(member_assign(_, _, _), State, State,
    "; TODO: member_assign not implemented\n").
codegen_statement(method_call(_, _, _), State, State,
    "; TODO: method_call not implemented\n").
codegen_statement(self_assign(_, _), State, State,
    "; TODO: self_assign not implemented\n").
codegen_statement(parent_call(_, _), State, State,
    "; TODO: parent_call not implemented\n").
codegen_statement(array_assign(_, _, _), State, State,
    "; TODO: array_assign not implemented\n").
codegen_statement(accept(_), State, State,
    "; TODO: accept loop not implemented\n").
codegen_statement(print(_), State, State,
    "; TODO: print not implemented\n").
codegen_statement(member_access(_, _), State, State, "").

%------------------------------------------------------------
% Catch-all
%------------------------------------------------------------

codegen_statement(Stmt, State, State, IR) :-
    format(atom(IR), '; Unhandled statement: ~w\n', [Stmt]).

%============================================================
% Expression Codegen
%============================================================

%------------------------------------------------------------
% Number literal
%------------------------------------------------------------

codegen_expr(number(N), State, State, N, "").
codegen_expr(neg(N), State, State, Result, "") :-
    Result is -N.

%------------------------------------------------------------
% String literal
%------------------------------------------------------------

codegen_expr(string(S), StateIn, StateOut, Result, IR) :-
    add_string_literal(S, StateIn, Index, StateOut),
    atom_length(S, Len),
    Len1 is Len + 1,
    next_temp(StateOut, Result, _),
    format(atom(IR), '  ~w = getelementptr [~d x i8], [~d x i8]* @.str.~d, i64 0, i64 0\n',
           [Result, Len1, Len1, Index]).

%------------------------------------------------------------
% Boolean literals
%------------------------------------------------------------

codegen_expr(true, State, State, '1', "").
codegen_expr(false, State, State, '0', "").

%------------------------------------------------------------
% Variable reference
%------------------------------------------------------------

codegen_expr(var(Name), StateIn, StateOut, Result, IR) :-
    next_temp(StateIn, Result, StateOut),
    ( member((Name, _), StateIn.vars)
    -> format(atom(IR), '  ~w = load i64, i64* %~w\n', [Result, Name])
    ;  format(atom(IR), '  ~w = load i64, i64* @~w\n', [Result, Name])
    ).

%------------------------------------------------------------
% Binary operations
%------------------------------------------------------------

codegen_expr(binop(Op, Left, Right), StateIn, StateOut, Result, IR) :-
    codegen_expr(Left, StateIn, State1, LeftResult, LeftIR),
    codegen_expr(Right, State1, State2, RightResult, RightIR),
    next_temp(State2, Result, StateOut),
    binop_to_llvm(Op, LeftResult, RightResult, Result, OpIR),
    atomics_to_string([LeftIR, RightIR, OpIR], IR).

binop_to_llvm('+', L, R, Res, IR) :-
    format(atom(IR), '  ~w = add i64 ~w, ~w\n', [Res, L, R]).
binop_to_llvm('-', L, R, Res, IR) :-
    format(atom(IR), '  ~w = sub i64 ~w, ~w\n', [Res, L, R]).
binop_to_llvm('*', L, R, Res, IR) :-
    format(atom(IR), '  ~w = mul i64 ~w, ~w\n', [Res, L, R]).
binop_to_llvm('/', L, R, Res, IR) :-
    format(atom(IR), '  ~w = sdiv i64 ~w, ~w\n', [Res, L, R]).
binop_to_llvm('%', L, R, Res, IR) :-
    format(atom(IR), '  ~w = srem i64 ~w, ~w\n', [Res, L, R]).

% Comparison operators (return i64: 0 or 1)
binop_to_llvm('=', L, R, Res, IR) :-
    format(atom(IR), '  ~w.cmp = icmp eq i64 ~w, ~w\n  ~w = zext i1 ~w.cmp to i64\n',
           [Res, L, R, Res, Res]).
binop_to_llvm('==', L, R, Res, IR) :-
    binop_to_llvm('=', L, R, Res, IR).
binop_to_llvm('!=', L, R, Res, IR) :-
    format(atom(IR), '  ~w.cmp = icmp ne i64 ~w, ~w\n  ~w = zext i1 ~w.cmp to i64\n',
           [Res, L, R, Res, Res]).
binop_to_llvm('<>', L, R, Res, IR) :-
    binop_to_llvm('!=', L, R, Res, IR).
binop_to_llvm('<', L, R, Res, IR) :-
    format(atom(IR), '  ~w.cmp = icmp slt i64 ~w, ~w\n  ~w = zext i1 ~w.cmp to i64\n',
           [Res, L, R, Res, Res]).
binop_to_llvm('>', L, R, Res, IR) :-
    format(atom(IR), '  ~w.cmp = icmp sgt i64 ~w, ~w\n  ~w = zext i1 ~w.cmp to i64\n',
           [Res, L, R, Res, Res]).
binop_to_llvm('<=', L, R, Res, IR) :-
    format(atom(IR), '  ~w.cmp = icmp sle i64 ~w, ~w\n  ~w = zext i1 ~w.cmp to i64\n',
           [Res, L, R, Res, Res]).
binop_to_llvm('>=', L, R, Res, IR) :-
    format(atom(IR), '  ~w.cmp = icmp sge i64 ~w, ~w\n  ~w = zext i1 ~w.cmp to i64\n',
           [Res, L, R, Res, Res]).

% Logical operators
binop_to_llvm(and, L, R, Res, IR) :-
    format(atom(IR), '  ~w = and i64 ~w, ~w\n', [Res, L, R]).
binop_to_llvm(or, L, R, Res, IR) :-
    format(atom(IR), '  ~w = or i64 ~w, ~w\n', [Res, L, R]).

% String concatenation (simplified - returns left operand for now)
binop_to_llvm('&', L, _, Res, IR) :-
    format(atom(IR), '  ~w = add i64 ~w, 0  ; TODO: string concat\n', [Res, L]).

%------------------------------------------------------------
% NOT operator
%------------------------------------------------------------

codegen_expr(not(Expr), StateIn, StateOut, Result, IR) :-
    codegen_expr(Expr, StateIn, State1, ExprResult, ExprIR),
    next_temp(State1, CmpResult, State2),
    next_temp(State2, Result, StateOut),
    format(atom(NotIR), '  ~w = icmp eq i64 ~w, 0\n  ~w = zext i1 ~w to i64\n',
           [CmpResult, ExprResult, Result, CmpResult]),
    atom_concat(ExprIR, NotIR, IR).

%------------------------------------------------------------
% Function calls in expressions
%------------------------------------------------------------

codegen_expr(call(Name, Args), StateIn, StateOut, Result, IR) :-
    codegen_call(Name, Args, StateIn, StateOut, Result, IR).

%------------------------------------------------------------
% Member access (simplified)
%------------------------------------------------------------

codegen_expr(member_access(_, _), StateIn, StateOut, '0', IR) :-
    format(atom(IR), '; TODO: member_access in expr\n', []),
    StateOut = StateIn.

codegen_expr(self_access(_), StateIn, StateIn, '0',
    "; TODO: self_access not implemented\n").

codegen_expr(method_call(_, _, _), StateIn, StateIn, '0',
    "; TODO: method_call expr not implemented\n").

%------------------------------------------------------------
% Control reference (GUI)
%------------------------------------------------------------

codegen_expr(control_ref(_), State, State, '0', "").
codegen_expr(picture(_), State, State, '0', "").

%------------------------------------------------------------
% Catch-all for expressions
%------------------------------------------------------------

codegen_expr(Expr, State, State, '0', IR) :-
    format(atom(IR), '; Unhandled expr: ~w\n', [Expr]).

%============================================================
% Function/Procedure Calls
%============================================================

codegen_call('MESSAGE', Args, StateIn, StateOut, '0', IR) :-
    % MESSAGE builtin -> printf
    ( Args = [Arg|_]
    -> codegen_expr(Arg, StateIn, State1, ArgResult, ArgIR),
       next_temp(State1, _, StateOut),
       format(atom(CallIR), '  call i32 @puts(i8* ~w)\n', [ArgResult]),
       atom_concat(ArgIR, CallIR, IR)
    ;  IR = "", StateOut = StateIn
    ).

codegen_call(Name, Args, StateIn, StateOut, Result, IR) :-
    Name \= 'MESSAGE',
    % Check if it's a user-defined procedure
    ( member(procedure(Name, _, _, _), StateIn.procedures)
    -> codegen_user_call(Name, Args, StateIn, StateOut, Result, IR)
    ;  % Unknown function - emit warning
       next_temp(StateIn, Result, StateOut),
       format(atom(IR), '  ~w = add i64 0, 0  ; Unknown function: ~w\n', [Result, Name])
    ).

codegen_user_call(Name, Args, StateIn, StateOut, Result, IR) :-
    codegen_args(Args, StateIn, State1, ArgResults, ArgsIR),
    next_temp(State1, Result, StateOut),
    format_arg_list(ArgResults, ArgList),
    format(atom(CallIR), '  ~w = call i64 @~w(~w)\n', [Result, Name, ArgList]),
    atom_concat(ArgsIR, CallIR, IR).

codegen_args([], State, State, [], "").
codegen_args([Arg|Args], StateIn, StateOut, [Result|Results], IR) :-
    codegen_expr(Arg, StateIn, State1, Result, ArgIR),
    codegen_args(Args, State1, StateOut, Results, RestIR),
    atom_concat(ArgIR, RestIR, IR).

format_arg_list([], "").
format_arg_list([Arg], ArgStr) :-
    format(atom(ArgStr), 'i64 ~w', [Arg]).
format_arg_list([Arg|Args], ArgList) :-
    Args \= [],
    format(atom(ArgStr), 'i64 ~w, ', [Arg]),
    format_arg_list(Args, RestArgs),
    atom_concat(ArgStr, RestArgs, ArgList).

%============================================================
% Utility Predicates
%============================================================

atomics_to_string(Atoms, String) :-
    atomic_list_concat(Atoms, String).

replace_nth0(0, [_|T], X, [X|T]) :- !.
replace_nth0(N, [H|T], X, [H|R]) :-
    N > 0,
    N1 is N - 1,
    replace_nth0(N1, T, X, R).

%============================================================
% Tests
%============================================================

:- use_module(library(plunit)).

:- begin_tests(clarion_llvm).

test(compile_number) :-
    empty_codegen_state(S),
    codegen_expr(number(42), S, _, Result, IR),
    Result = 42,
    IR = "".

test(compile_binop) :-
    empty_codegen_state(S),
    codegen_expr(binop('+', number(1), number(2)), S, _, _, IR),
    sub_atom(IR, _, _, _, 'add i64').

test(compile_if) :-
    empty_codegen_state(S),
    codegen_statement(if(number(1), [return], [], []), S, _, IR),
    sub_atom(IR, _, _, _, 'icmp'),
    sub_atom(IR, _, _, _, 'br i1').

:- end_tests(clarion_llvm).
